# Generated by Django 6.0.7 on 2026-09-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('out_of_delivery', 'OUT_OF_DELIVERY'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default='pending', max_length=30),
        ),
    ]
