# Generated by Django 6.0.7 on 2026-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], default='pending', max_length=30),
        ),
    ]
