# Generated by Django 6.0.7 on 2026-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('out_of_delivery', 'OUT FOR DELIVERY'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default='pending', max_length=30),
        ),
    ]
