# Generated by Django 6.0.7 on 2026-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_status_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'CASH ON DELIVERY'), ('online', 'ONLINE PAYMENT')], max_length=30),
        ),
    ]
